// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn3w6sTXfqJTl2QODOf6uOd13f-K58Kso',
    appId: '1:990022161886:web:44d5b0c46ba896b5c1394f',
    messagingSenderId: '990022161886',
    projectId: 'alarm-ing',
    authDomain: 'alarm-ing.firebaseapp.com',
    storageBucket: 'alarm-ing.appspot.com',
    measurementId: 'G-XJMG5MWCPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWunyeQjf0UqDZqzPU7GYE3Emc9Q7xFuc',
    appId: '1:990022161886:android:4b2064b7a2132562c1394f',
    messagingSenderId: '990022161886',
    projectId: 'alarm-ing',
    storageBucket: 'alarm-ing.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVuGxOV7qtlH004aMhDSNuM4xCXKSTC5o',
    appId: '1:990022161886:ios:23f852b406941b18c1394f',
    messagingSenderId: '990022161886',
    projectId: 'alarm-ing',
    storageBucket: 'alarm-ing.appspot.com',
    iosClientId:
        '990022161886-6avbv93n15o96pj3hjhsahuk79a8oc6j.apps.googleusercontent.com',
    iosBundleId: 'com.example.alarming',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVuGxOV7qtlH004aMhDSNuM4xCXKSTC5o',
    appId: '1:990022161886:ios:23f852b406941b18c1394f',
    messagingSenderId: '990022161886',
    projectId: 'alarm-ing',
    storageBucket: 'alarm-ing.appspot.com',
    iosClientId:
        '990022161886-6avbv93n15o96pj3hjhsahuk79a8oc6j.apps.googleusercontent.com',
    iosBundleId: 'com.example.alarming',
  );
}
